import type { DiagramTemplate } from './diagramTypes';

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  {
    id: 'tpl-aws-3tier',
    title: 'AWS 3-Tier Highly Available Web App',
    category: 'AWS Architecture',
    description: 'CloudFront, ALB, Auto Scaling EC2 across Multi-AZ, and Aurora MySQL with Read Replicas & ElastiCache.',
    diagram: {
      name: 'AWS 3-Tier Web Architecture',
      description: 'Production Multi-AZ Architecture with VPC isolation',
      viewport: { x: 50, y: 50, zoom: 0.85 },
      background: 'grid',
      showGrid: true,
      snapToGrid: true,
      frames: [
        {
          id: 'frame-vpc',
          title: 'AWS VPC (10.0.0.0/16)',
          x: 220,
          y: 40,
          width: 820,
          height: 600,
          style: { fill: '#0f172a15', stroke: '#8b5cf6', strokeDash: 'dashed' },
        },
        {
          id: 'frame-public',
          title: 'Public Subnet (ALB)',
          x: 260,
          y: 90,
          width: 740,
          height: 120,
          style: { fill: '#0284c710', stroke: '#0284c7', strokeDash: 'dashed' },
        },
        {
          id: 'frame-private-app',
          title: 'Private App Subnet (Auto Scaling EC2)',
          x: 260,
          y: 240,
          width: 740,
          height: 160,
          style: { fill: '#10b98110', stroke: '#10b981', strokeDash: 'dashed' },
        },
        {
          id: 'frame-private-db',
          title: 'Private Data Subnet (Aurora & Redis)',
          x: 260,
          y: 430,
          width: 740,
          height: 170,
          style: { fill: '#f59e0b10', stroke: '#f59e0b', strokeDash: 'dashed' },
        },
      ],
      nodes: [
        {
          id: 'n-user',
          type: 'rectangle',
          label: 'Global Users\n(Web & Mobile)',
          x: 40,
          y: 260,
          width: 130,
          height: 70,
          style: { fill: '#1e293b', stroke: '#38bdf8', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
        },
        {
          id: 'n-cf',
          type: 'aws-service',
          label: 'Amazon CloudFront\n(Edge CDN & WAF)',
          x: 50,
          y: 110,
          width: 150,
          height: 75,
          style: { fill: '#1e293b', stroke: '#a855f7', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Networking', icon: 'Globe' },
        },
        {
          id: 'n-alb',
          type: 'aws-service',
          label: 'Application Load Balancer\n(Internet-facing ALB)',
          x: 480,
          y: 110,
          width: 180,
          height: 75,
          style: { fill: '#1e293b', stroke: '#0284c7', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Networking', icon: 'Network' },
        },
        {
          id: 'n-ec2-1',
          type: 'aws-service',
          label: 'EC2 App Node (AZ-1)\nNode.js / Express',
          x: 320,
          y: 280,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#10b981', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Compute', icon: 'Cpu' },
        },
        {
          id: 'n-ec2-2',
          type: 'aws-service',
          label: 'EC2 App Node (AZ-2)\nNode.js / Express',
          x: 640,
          y: 280,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#10b981', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Compute', icon: 'Cpu' },
        },
        {
          id: 'n-redis',
          type: 'aws-service',
          label: 'Amazon ElastiCache\n(Redis Cluster)',
          x: 320,
          y: 470,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#ec4899', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Database', icon: 'Zap' },
        },
        {
          id: 'n-aurora',
          type: 'aws-service',
          label: 'Amazon Aurora MySQL\n(Multi-AZ Cluster)',
          x: 640,
          y: 470,
          width: 170,
          height: 75,
          style: { fill: '#1e293b', stroke: '#f59e0b', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Database', icon: 'Database' },
        },
      ],
      edges: [
        {
          id: 'e-1',
          sourceNodeId: 'n-user',
          targetNodeId: 'n-cf',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'HTTPS',
          animated: true,
        },
        {
          id: 'e-2',
          sourceNodeId: 'n-cf',
          targetNodeId: 'n-alb',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#a855f7',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Origin Request',
          animated: true,
        },
        {
          id: 'e-3',
          sourceNodeId: 'n-alb',
          targetNodeId: 'n-ec2-1',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#0284c7',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Target Group AZ-A',
        },
        {
          id: 'e-4',
          sourceNodeId: 'n-alb',
          targetNodeId: 'n-ec2-2',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#0284c7',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Target Group AZ-B',
        },
        {
          id: 'e-5',
          sourceNodeId: 'n-ec2-1',
          targetNodeId: 'n-redis',
          type: 'orthogonal',
          lineStyle: 'dashed',
          strokeColor: '#ec4899',
          strokeWidth: 1.5,
          endArrow: 'arrow',
          label: 'Session / Cache',
        },
        {
          id: 'e-6',
          sourceNodeId: 'n-ec2-2',
          targetNodeId: 'n-redis',
          type: 'orthogonal',
          lineStyle: 'dashed',
          strokeColor: '#ec4899',
          strokeWidth: 1.5,
          endArrow: 'arrow',
        },
        {
          id: 'e-7',
          sourceNodeId: 'n-ec2-1',
          targetNodeId: 'n-aurora',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'SQL Read/Write',
        },
        {
          id: 'e-8',
          sourceNodeId: 'n-ec2-2',
          targetNodeId: 'n-aurora',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          endArrow: 'arrow',
        },
      ],
      presentationSteps: [
        {
          id: 'step-1',
          stepNumber: 1,
          title: 'Edge Caching & Security',
          explanation: 'Users send HTTPS requests hitting CloudFront Edge Locations with AWS WAF inspection.',
          highlightNodeIds: ['n-user', 'n-cf'],
          highlightEdgeIds: ['e-1'],
        },
        {
          id: 'step-2',
          stepNumber: 2,
          title: 'Load Balancing to Compute Tier',
          explanation: 'ALB receives dynamic traffic and routes health-checked requests to EC2 Auto Scaling instances.',
          highlightNodeIds: ['n-alb', 'n-ec2-1', 'n-ec2-2'],
          highlightEdgeIds: ['e-2', 'e-3', 'e-4'],
        },
        {
          id: 'step-3',
          stepNumber: 3,
          title: 'Data Persistence & High-Speed Cache',
          explanation: 'App instances query ElastiCache Redis for sub-millisecond session reads and write to Aurora Multi-AZ.',
          highlightNodeIds: ['n-redis', 'n-aurora'],
          highlightEdgeIds: ['e-5', 'e-6', 'e-7', 'e-8'],
        },
      ],
    },
  },
  {
    id: 'tpl-aws-serverless',
    title: 'AWS Serverless Event-Driven Microservices',
    category: 'AWS Architecture',
    description: 'API Gateway, Lambda Functions, DynamoDB with Streams, SQS Queue, and EventBridge bus.',
    diagram: {
      name: 'Serverless Event-Driven Pattern',
      description: 'Asynchronous event decoupling with SQS and EventBridge',
      viewport: { x: 50, y: 50, zoom: 0.85 },
      background: 'grid',
      showGrid: true,
      snapToGrid: true,
      frames: [],
      nodes: [
        {
          id: 'n-client',
          type: 'rectangle',
          label: 'Single Page App\n(React / CloudFront)',
          x: 40,
          y: 200,
          width: 140,
          height: 70,
          style: { fill: '#1e293b', stroke: '#38bdf8', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
        },
        {
          id: 'n-apigw',
          type: 'aws-service',
          label: 'Amazon API Gateway\n(REST / HTTP API)',
          x: 240,
          y: 200,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#f97316', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Serverless', icon: 'Network' },
        },
        {
          id: 'n-lambda-order',
          type: 'aws-service',
          label: 'Order Lambda\n(Sync Processing)',
          x: 460,
          y: 120,
          width: 150,
          height: 75,
          style: { fill: '#1e293b', stroke: '#eab308', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Serverless', icon: 'Zap' },
        },
        {
          id: 'n-dynamo',
          type: 'aws-service',
          label: 'Orders DynamoDB\n(Single-Table Design)',
          x: 680,
          y: 120,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#3b82f6', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Database', icon: 'Database' },
        },
        {
          id: 'n-sqs',
          type: 'aws-service',
          label: 'Amazon SQS Queue\n(Order Processing FIFO)',
          x: 460,
          y: 290,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#ec4899', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Serverless', icon: 'Layers' },
        },
        {
          id: 'n-eventbridge',
          type: 'aws-service',
          label: 'Amazon EventBridge\n(Default Event Bus)',
          x: 680,
          y: 290,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#8b5cf6', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Serverless', icon: 'Workflow' },
        },
        {
          id: 'n-s3-lake',
          type: 'aws-service',
          label: 'Amazon S3 Lake\n(Analytics Archive)',
          x: 900,
          y: 290,
          width: 150,
          height: 75,
          style: { fill: '#1e293b', stroke: '#10b981', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Storage', icon: 'HardDrive' },
        },
      ],
      edges: [
        {
          id: 'e-s1',
          sourceNodeId: 'n-client',
          targetNodeId: 'n-apigw',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'POST /orders',
          animated: true,
        },
        {
          id: 'e-s2',
          sourceNodeId: 'n-apigw',
          targetNodeId: 'n-lambda-order',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#eab308',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Sync Invoke',
        },
        {
          id: 'e-s3',
          sourceNodeId: 'n-lambda-order',
          targetNodeId: 'n-dynamo',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'PutItem',
        },
        {
          id: 'e-s4',
          sourceNodeId: 'n-dynamo',
          targetNodeId: 'n-sqs',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#ec4899',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'DynamoDB Streams',
          animated: true,
        },
        {
          id: 'e-s5',
          sourceNodeId: 'n-sqs',
          targetNodeId: 'n-eventbridge',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#8b5cf6',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Publish Event',
        },
        {
          id: 'e-s6',
          sourceNodeId: 'n-eventbridge',
          targetNodeId: 'n-s3-lake',
          type: 'orthogonal',
          lineStyle: 'dashed',
          strokeColor: '#10b981',
          strokeWidth: 1.5,
          endArrow: 'arrow',
          label: 'Firehose Archive',
        },
      ],
      presentationSteps: [
        {
          id: 'step-s1',
          stepNumber: 1,
          title: 'Synchronous Order Intake',
          explanation: 'Frontend submits order via API Gateway which invokes Order Lambda to validate and persist in DynamoDB.',
          highlightNodeIds: ['n-client', 'n-apigw', 'n-lambda-order', 'n-dynamo'],
          highlightEdgeIds: ['e-s1', 'e-s2', 'e-s3'],
        },
        {
          id: 'step-s2',
          stepNumber: 2,
          title: 'Asynchronous Stream Decoupling',
          explanation: 'DynamoDB Streams triggers an SQS queue to buffer downstream payment and inventory fulfillment.',
          highlightNodeIds: ['n-dynamo', 'n-sqs'],
          highlightEdgeIds: ['e-s4'],
        },
        {
          id: 'step-s3',
          stepNumber: 3,
          title: 'Event Routing & Data Lake Archive',
          explanation: 'EventBridge routes order status events to third-party services and archives records into S3 Data Lake.',
          highlightNodeIds: ['n-sqs', 'n-eventbridge', 'n-s3-lake'],
          highlightEdgeIds: ['e-s5', 'e-s6'],
        },
      ],
    },
  },
  {
    id: 'tpl-genai-rag',
    title: 'Generative AI RAG Architecture (Amazon Bedrock)',
    category: 'AWS Architecture',
    description: 'RAG Pipeline with Bedrock Claude 3, OpenSearch Vector Store, S3 Document Lake & API Gateway.',
    diagram: {
      name: 'Generative AI RAG Pipeline',
      description: 'Retrieval-Augmented Generation with Vector Embeddings',
      viewport: { x: 50, y: 50, zoom: 0.85 },
      background: 'dot',
      showGrid: true,
      snapToGrid: true,
      frames: [
        {
          id: 'frame-knowledge',
          title: 'Knowledge Ingestion & Vector Pipeline',
          x: 280,
          y: 60,
          width: 680,
          height: 170,
          style: { fill: '#6366f110', stroke: '#6366f1', strokeDash: 'dashed' },
        },
      ],
      nodes: [
        {
          id: 'n-rag-user',
          type: 'rectangle',
          label: 'User Query\n("Explain AWS VPC")',
          x: 40,
          y: 310,
          width: 140,
          height: 70,
          style: { fill: '#1e293b', stroke: '#38bdf8', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
        },
        {
          id: 'n-rag-apigw',
          type: 'aws-service',
          label: 'API Gateway\n(WebSocket / Streaming)',
          x: 230,
          y: 310,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#f97316', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Serverless', icon: 'Network' },
        },
        {
          id: 'n-rag-s3',
          type: 'aws-service',
          label: 'Amazon S3\n(PDF / Markdown Docs)',
          x: 320,
          y: 110,
          width: 150,
          height: 70,
          style: { fill: '#1e293b', stroke: '#10b981', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Storage', icon: 'HardDrive' },
        },
        {
          id: 'n-rag-titan',
          type: 'aws-service',
          label: 'Amazon Titan Embed\n(Vector Chunking)',
          x: 520,
          y: 110,
          width: 160,
          height: 70,
          style: { fill: '#1e293b', stroke: '#8b5cf6', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'AI/ML', icon: 'Sparkles' },
        },
        {
          id: 'n-rag-opensearch',
          type: 'aws-service',
          label: 'OpenSearch Vector DB\n(k-NN Hybrid Search)',
          x: 740,
          y: 110,
          width: 170,
          height: 70,
          style: { fill: '#1e293b', stroke: '#06b6d4', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Database', icon: 'Search' },
        },
        {
          id: 'n-rag-orchestrator',
          type: 'aws-service',
          label: 'Orchestrator Lambda\n(Context Augmenter)',
          x: 470,
          y: 310,
          width: 160,
          height: 75,
          style: { fill: '#1e293b', stroke: '#eab308', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Serverless', icon: 'Zap' },
        },
        {
          id: 'n-rag-bedrock',
          type: 'aws-service',
          label: 'Amazon Bedrock\n(Claude 3 / Llama 3)',
          x: 740,
          y: 310,
          width: 170,
          height: 75,
          style: { fill: '#1e293b', stroke: '#a855f7', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'AI/ML', icon: 'Bot' },
        },
      ],
      edges: [
        {
          id: 'er-1',
          sourceNodeId: 'n-rag-s3',
          targetNodeId: 'n-rag-titan',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#8b5cf6',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Extract text',
        },
        {
          id: 'er-2',
          sourceNodeId: 'n-rag-titan',
          targetNodeId: 'n-rag-opensearch',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#06b6d4',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Index Vectors',
        },
        {
          id: 'er-3',
          sourceNodeId: 'n-rag-user',
          targetNodeId: 'n-rag-apigw',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          endArrow: 'arrow',
          animated: true,
        },
        {
          id: 'er-4',
          sourceNodeId: 'n-rag-apigw',
          targetNodeId: 'n-rag-orchestrator',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#eab308',
          strokeWidth: 2,
          endArrow: 'arrow',
        },
        {
          id: 'er-5',
          sourceNodeId: 'n-rag-orchestrator',
          targetNodeId: 'n-rag-opensearch',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#06b6d4',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Semantic Search',
        },
        {
          id: 'er-6',
          sourceNodeId: 'n-rag-orchestrator',
          targetNodeId: 'n-rag-bedrock',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#a855f7',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Prompt + Chunks',
          animated: true,
        },
      ],
    },
  },
  {
    id: 'tpl-sys-url-shortener',
    title: 'System Design: Scalable URL Shortener (Bitly)',
    category: 'System Design',
    description: 'High concurrency URL shortening system handling 100K QPS with Redis Cache and Cassandra/PostgreSQL.',
    diagram: {
      name: 'Scalable URL Shortener Design',
      description: 'Distributed cache & unique ID generation (Snowflake)',
      viewport: { x: 50, y: 50, zoom: 0.85 },
      background: 'grid',
      showGrid: true,
      snapToGrid: true,
      frames: [],
      nodes: [
        {
          id: 'n-client-short',
          type: 'rectangle',
          label: 'User / Browser\n(short.ly/xyz123)',
          x: 40,
          y: 200,
          width: 140,
          height: 70,
          style: { fill: '#1e293b', stroke: '#38bdf8', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
        },
        {
          id: 'n-lb-short',
          type: 'diamond',
          label: 'Nginx / ALB\nLoad Balancer',
          x: 230,
          y: 195,
          width: 130,
          height: 80,
          style: { fill: '#1e293b', stroke: '#f59e0b', strokeWidth: 2, textColor: '#f8fafc' },
        },
        {
          id: 'n-svc-short',
          type: 'rounded-rect',
          label: 'URL Shortener Service\n(Go / Node Cluster)',
          x: 420,
          y: 200,
          width: 160,
          height: 70,
          style: { fill: '#1e293b', stroke: '#10b981', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 12 },
        },
        {
          id: 'n-redis-short',
          type: 'cylinder',
          label: 'Redis Cache\n(LRU Top 20% URLs)',
          x: 640,
          y: 120,
          width: 150,
          height: 80,
          style: { fill: '#1e293b', stroke: '#ec4899', strokeWidth: 2, textColor: '#f8fafc' },
        },
        {
          id: 'n-db-short',
          type: 'cylinder',
          label: 'PostgreSQL / DynamoDB\n(Sharded by Base62 Hash)',
          x: 640,
          y: 270,
          width: 170,
          height: 80,
          style: { fill: '#1e293b', stroke: '#3b82f6', strokeWidth: 2, textColor: '#f8fafc' },
        },
      ],
      edges: [
        {
          id: 'es-1',
          sourceNodeId: 'n-client-short',
          targetNodeId: 'n-lb-short',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#38bdf8',
          strokeWidth: 2,
          endArrow: 'arrow',
          animated: true,
        },
        {
          id: 'es-2',
          sourceNodeId: 'n-lb-short',
          targetNodeId: 'n-svc-short',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          endArrow: 'arrow',
        },
        {
          id: 'es-3',
          sourceNodeId: 'n-svc-short',
          targetNodeId: 'n-redis-short',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#ec4899',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: '1. Check Cache',
        },
        {
          id: 'es-4',
          sourceNodeId: 'n-svc-short',
          targetNodeId: 'n-db-short',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: '2. Cache Miss',
        },
      ],
    },
  },
  {
    id: 'tpl-devops-cicd',
    title: 'DevOps: Modern GitOps & CI/CD Pipeline',
    category: 'DevOps',
    description: 'GitHub Actions, automated security scanning, Amazon ECR, and ArgoCD declarative continuous delivery on EKS.',
    diagram: {
      name: 'GitOps Continuous Delivery',
      description: 'Declarative Kubernetes deployments with ArgoCD',
      viewport: { x: 50, y: 50, zoom: 0.85 },
      background: 'lines',
      showGrid: true,
      snapToGrid: true,
      frames: [],
      nodes: [
        {
          id: 'n-git',
          type: 'rectangle',
          label: 'GitHub Repo\n(Git Commit)',
          x: 40,
          y: 180,
          width: 130,
          height: 70,
          style: { fill: '#1e293b', stroke: '#f8fafc', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
        },
        {
          id: 'n-actions',
          type: 'rounded-rect',
          label: 'GitHub Actions\n(Lint, Test, Docker Build)',
          x: 230,
          y: 180,
          width: 170,
          height: 70,
          style: { fill: '#1e293b', stroke: '#0284c7', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
        },
        {
          id: 'n-ecr',
          type: 'aws-service',
          label: 'Amazon ECR\n(OCI Image Registry)',
          x: 460,
          y: 180,
          width: 150,
          height: 70,
          style: { fill: '#1e293b', stroke: '#f59e0b', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Containers', icon: 'Box' },
        },
        {
          id: 'n-argo',
          type: 'aws-service',
          label: 'ArgoCD Operator\n(GitOps Reconciler)',
          x: 670,
          y: 180,
          width: 160,
          height: 70,
          style: { fill: '#1e293b', stroke: '#10b981', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Containers', icon: 'RefreshCw' },
        },
        {
          id: 'n-eks',
          type: 'aws-service',
          label: 'Amazon EKS Cluster\n(Production Pods)',
          x: 890,
          y: 180,
          width: 160,
          height: 70,
          style: { fill: '#1e293b', stroke: '#8b5cf6', strokeWidth: 2, textColor: '#f8fafc', borderRadius: 8 },
          data: { serviceCategory: 'Containers', icon: 'Layers' },
        },
      ],
      edges: [
        {
          id: 'ed-1',
          sourceNodeId: 'n-git',
          targetNodeId: 'n-actions',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#0284c7',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Webhook',
          animated: true,
        },
        {
          id: 'ed-2',
          sourceNodeId: 'n-actions',
          targetNodeId: 'n-ecr',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Push Image',
        },
        {
          id: 'ed-3',
          sourceNodeId: 'n-argo',
          targetNodeId: 'n-ecr',
          type: 'orthogonal',
          lineStyle: 'dashed',
          strokeColor: '#f59e0b',
          strokeWidth: 1.5,
          endArrow: 'arrow',
          label: 'Poll New Digest',
        },
        {
          id: 'ed-4',
          sourceNodeId: 'n-argo',
          targetNodeId: 'n-eks',
          type: 'orthogonal',
          lineStyle: 'solid',
          strokeColor: '#10b981',
          strokeWidth: 2,
          endArrow: 'arrow',
          label: 'Kube Apply',
          animated: true,
        },
      ],
    },
  },
];
