import type { Flashcard } from './types';

export const FLASHCARDS: Flashcard[] = [
  // --- SERVICES DECK ---
  {
    id: 'fc-s3-tiers',
    deckId: 'services',
    title: 'S3 Storage Classes & Durability',
    category: 'Storage',
    front: 'What are the key differences between S3 Standard-IA, S3 One Zone-IA, and S3 Glacier Flexible Retrieval?',
    back: '• Standard-IA: Rapid access, 11 9s durability, 3+ AZs, retrieval fee per GB, 30-day min storage.\n• One Zone-IA: 11 9s durability, SINGLE AZ only (data lost if AZ destroyed), 20% cheaper than Standard-IA.\n• Glacier Flexible: 11 9s durability across 3+ AZs, 90-day min storage. Retrieval options: Expedited (1-5 min), Standard (3-5 hr), Bulk (5-12 hr).',
    keyTakeaway: 'One Zone-IA is for easily reproducible data; Glacier Flexible has 3 retrieval tiers (Expedited/Standard/Bulk).',
    commonTrap: 'One Zone-IA has 11 9s durability within that single zone, but 0% availability if the AZ is destroyed.',
    relatedServices: ['s3', 'glacier'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-ebs-types',
    deckId: 'services',
    title: 'EBS Volume Types Selection',
    category: 'Storage',
    front: 'When do you choose gp3, io2, st1, or sc1 EBS volume types?',
    back: '• gp3: Default General Purpose SSD; baseline 3,000 IOPS & 125 MB/s independent of storage size.\n• io2 / io2 Block Express: Mission-critical relational DBs (up to 256,000 IOPS, 99.999% durability, supports Multi-Attach).\n• st1 (Throughput Optimized HDD): Big data, data warehouses, log processing. CANNOT BE BOOT VOLUME.\n• sc1 (Cold HDD): Lowest cost cold storage for infrequently accessed data. CANNOT BE BOOT VOLUME.',
    keyTakeaway: 'st1 and sc1 HDD volumes cannot be used as EC2 boot volumes.',
    commonTrap: 'Assuming io1/io2 Multi-Attach works like a shared network drive — it requires a cluster-aware file system (like GFS2) to prevent corruption.',
    relatedServices: ['ebs', 'ec2'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-kms-keys',
    deckId: 'services',
    title: 'AWS KMS Key Types & Rotation',
    category: 'Security',
    front: 'Compare AWS Owned, AWS Managed, and Customer Managed KMS Keys.',
    back: '• AWS Owned: Free, internal to AWS (you cannot view, manage, or audit in CloudTrail).\n• AWS Managed: Created by AWS per service (e.g., aws/s3). Free key usage, automatic rotation every 1 year. Cannot change key policy.\n• Customer Managed (CMK): $1/month + API requests. Full control over key policy, grants, and aliases. Optional automatic rotation every 1 year. Supports cross-account KMS policies.',
    keyTakeaway: 'For compliance requiring auditing or custom key policies, Customer Managed Keys are required.',
    commonTrap: 'IAM policies alone cannot grant access to a KMS key if the KMS Key Policy does not permit the calling principal.',
    relatedServices: ['kms', 'iam', 's3'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-vpc-endpoints',
    deckId: 'services',
    title: 'VPC Gateway Endpoints vs Interface Endpoints (PrivateLink)',
    category: 'Networking',
    front: 'What AWS services use Gateway Endpoints versus Interface Endpoints?',
    back: '• Gateway Endpoints: FREE of charge. Target route table entry. ONLY supports Amazon S3 and Amazon DynamoDB.\n• Interface Endpoints (AWS PrivateLink): Hourly fee + data processing fee. Provisions an ENI with a private IP inside your VPC. Supports 100+ AWS services (SQS, SNS, Secrets Manager, etc.) and third-party SaaS.',
    keyTakeaway: 'Gateway Endpoints = S3 & DynamoDB (Free). Interface Endpoints = everything else (Private ENI, billable).',
    commonTrap: 'Trying to configure a Gateway Endpoint for SQS or SSM — they only support Interface Endpoints.',
    relatedServices: ['vpc', 's3', 'dynamodb'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-sqs-types',
    deckId: 'services',
    title: 'SQS Standard vs FIFO Queues',
    category: 'Integration',
    front: 'What are the throughput, ordering, and deduplication differences between SQS Standard and FIFO?',
    back: '• Standard Queue: Unlimited throughput, at-least-once delivery, best-effort ordering (duplicates possible).\n• FIFO Queue: Exactly-once processing, strict first-in-first-out order. Requires Message Group ID (for grouped ordering) and Message Deduplication ID (5-min deduplication window). Throughput: up to 3,000 msg/s with batching/high-throughput mode.',
    keyTakeaway: 'FIFO = strict order + exactly once. Standard = infinite scale + at least once.',
    commonTrap: 'If the question does not strictly require order and deduplication, choose Standard for lowest cost and unlimited scale.',
    relatedServices: ['sqs', 'sns'],
    box: 1,
    reviewsCount: 0,
  },

  // --- DOMAINS DECK ---
  {
    id: 'fc-d1-least-privilege',
    deckId: 'domains',
    title: 'Domain 1: IAM Least Privilege & Cross-Account',
    category: 'Domain 1: Secure',
    front: 'How do you allow an EC2 instance in Account A to read objects from an S3 bucket in Account B securely?',
    back: '1. In Account A: Create an IAM Role for EC2 with permissions to assume a role or access S3.\n2. In Account B: Add a Bucket Policy on the S3 bucket granting `s3:GetObject` to Account A\'s IAM Role ARN.\n3. (Alternatively): Account A\'s EC2 assumes an IAM Role in Account B using AWS STS `AssumeRole`. Never use IAM user access keys.',
    keyTakeaway: 'Cross-account S3 access requires trust: either via S3 Bucket Policy in destination or STS AssumeRole.',
    commonTrap: 'Creating an IAM user with access keys and storing them in an EC2 config file is an automatic anti-pattern on AWS exams.',
    relatedServices: ['iam', 's3', 'sts'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-d2-rds-ha',
    deckId: 'domains',
    title: 'Domain 2: RDS High Availability & Disaster Recovery',
    category: 'Domain 2: Resilient',
    front: 'What happens during an RDS Multi-AZ automatic failover?',
    back: '• Failover trigger: Loss of primary AZ, primary DB crash, compute failure, or manual reboot with failover.\n• Process: RDS automatically promotes the standby DB replica in the secondary AZ to become the new primary.\n• DNS Endpoint: The DB endpoint DNS record is updated to point to the new primary. Application connection strings DO NOT need to change!\n• Time: Typically completes in 60 to 120 seconds (under 30 seconds for Aurora).',
    keyTakeaway: 'Multi-AZ failover is transparent: same DNS endpoint, synchronous replication, zero data loss.',
    commonTrap: 'Thinking you need to change your application configuration or Route 53 records during RDS Multi-AZ failover — RDS handles DNS propagation automatically.',
    relatedServices: ['rds', 'aurora', 'route53'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-d3-caching',
    deckId: 'domains',
    title: 'Domain 3: High-Performing Multi-Tier Caching',
    category: 'Domain 3: Performance',
    front: 'Where should caching be implemented at each layer of a modern AWS web architecture?',
    back: '• Edge Layer: Amazon CloudFront for static assets and API caching.\n• API Layer: Amazon API Gateway built-in cache (TTL up to 300s).\n• Application / Session Layer: Amazon ElastiCache (Redis / Memcached) for session state and database query results.\n• Database Layer: DynamoDB Accelerator (DAX) for DynamoDB microsecond reads; RDS Read Replicas for relational read scaling.',
    keyTakeaway: 'Always push cache as close to the user as possible (CloudFront -> API Gateway -> ElastiCache/DAX -> Read Replicas).',
    commonTrap: 'Using ElastiCache for DynamoDB: DAX is much simpler because it is drop-in API compatible with zero application refactoring.',
    relatedServices: ['cloudfront', 'elasticache', 'dynamodb', 'rds'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-d4-cost-reduction',
    deckId: 'domains',
    title: 'Domain 4: Cost Optimization Best Practices',
    category: 'Domain 4: Cost',
    front: 'What are the top 4 architectural levers to minimize EC2 and storage costs?',
    back: '1. Compute: Use Spot Instances for stateless batch jobs (up to 90% off), Savings Plans / Reserved Instances for steady-state 24/7 baselines (up to 72% off).\n2. Storage: S3 Lifecycle policies to transition old objects to Glacier Flexible or Deep Archive ($0.00099/GB/mo).\n3. Block Storage: Convert legacy EBS gp2 volumes to gp3 (20% lower cost per GB + independent IOPS/throughput).\n4. Networking: Use Gateway Endpoints for S3/DynamoDB instead of routing through NAT Gateways ($0.045/GB data processing fee).',
    keyTakeaway: 'Always replace gp2 with gp3, use S3 Lifecycle, and bypass NAT Gateways using VPC Gateway Endpoints.',
    commonTrap: 'NAT Gateway data processing fees can balloon bills. S3 traffic from private subnets should ALWAYS go through a free S3 Gateway Endpoint.',
    relatedServices: ['ec2', 's3', 'ebs', 'vpc'],
    box: 1,
    reviewsCount: 0,
  },

  // --- TRAPS DECK ---
  {
    id: 'fc-trap-nlb-ip',
    deckId: 'traps',
    title: 'Exam Trap: ALB vs NLB Static IP Requirement',
    category: 'Trap',
    front: 'A client application requires connecting to your AWS load balancer using a fixed, static public IP address. Can you use an ALB?',
    back: 'NO. ALB resolves to dynamic IP addresses that scale automatically. If a fixed static IP is required:\n• Solution 1: Use a Network Load Balancer (NLB) with Elastic IPs attached per AZ.\n• Solution 2: Place AWS Global Accelerator in front of the Application Load Balancer (ALB provides 2 static Anycast IPs).',
    keyTakeaway: 'ALB = DNS only. NLB or Global Accelerator = Static IPs.',
    commonTrap: 'Trying to assign an Elastic IP directly to an ALB (impossible in AWS).',
    relatedServices: ['alb-nlb', 'global-accelerator'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-trap-rds-standby',
    deckId: 'traps',
    title: 'Exam Trap: Querying RDS Multi-AZ Standby',
    category: 'Trap',
    front: 'Can your analytics or reporting team run read-heavy SQL queries against the RDS Multi-AZ standby instance to reduce load on the primary?',
    back: 'ABSOLUTELY NOT. The RDS Multi-AZ standby is passive and cannot accept any connections or queries.\n• Correct Solution: Provision an RDS Read Replica (which has its own DNS endpoint) and point reporting queries there.',
    keyTakeaway: 'Multi-AZ Standby = Failover ONLY (no reads). Read Replica = Reads allowed.',
    commonTrap: 'Selecting Multi-AZ as the solution for "scaling read traffic" or "offloading reporting queries".',
    relatedServices: ['rds', 'aurora'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-trap-s3-multipart',
    deckId: 'traps',
    title: 'Exam Trap: S3 Object Upload Size Thresholds',
    category: 'Trap',
    front: 'What is the maximum single PUT upload size in S3, and when is Multipart Upload required?',
    back: '• Single PUT limit: 5 GB maximum.\n• Multipart Upload: RECOMMENDED for objects > 100 MB, but MANDATORY for objects > 5 GB.\n• Maximum S3 object size: 5 TB.',
    keyTakeaway: 'Objects > 5 GB MUST use Multipart Upload. Max object size is 5 TB.',
    commonTrap: 'Choosing a single PUT operation for a 10 GB file (fails with HTTP 400).',
    relatedServices: ['s3'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-trap-lambda-timeout',
    deckId: 'traps',
    title: 'Exam Trap: Lambda Execution Timeout Limit',
    category: 'Trap',
    front: 'An ETL job currently runs for 45 minutes every night. Can you migrate this script to AWS Lambda to save costs?',
    back: 'NO. AWS Lambda has a hard maximum execution timeout of 15 minutes (900 seconds).\n• Correct Solutions: AWS Step Functions orchestrating multiple Lambda tasks, AWS Batch, or Amazon ECS / Fargate container tasks.',
    keyTakeaway: 'Lambda maximum runtime is 15 minutes. For longer jobs, use ECS Fargate or AWS Batch.',
    commonTrap: 'Picking Lambda for batch processing jobs that exceed 15 minutes runtime.',
    relatedServices: ['lambda', 'ecs-fargate'],
    box: 1,
    reviewsCount: 0,
  },

  // --- COMPARISONS DECK ---
  {
    id: 'fc-comp-kinesis-vs-sqs',
    deckId: 'comparisons',
    title: 'Comparison: Kinesis Data Streams vs SQS',
    category: 'Integration',
    front: 'When should you choose Amazon Kinesis Data Streams over Amazon SQS?',
    back: '• Choose Kinesis Data Streams when: Real-time streaming analytics, multiple applications consuming the SAME stream concurrently at their own pace, strict per-partition ordering, replayable data (retention 24h to 365 days).\n• Choose SQS when: Asynchronous message decoupling, individual message acknowledgement and deletion, horizontal worker auto-scaling.',
    keyTakeaway: 'Kinesis = multi-consumer replayable stream. SQS = message queue where message is deleted after processing.',
    commonTrap: 'Using SQS when multiple independent applications need to read the same message stream without fanout setup.',
    relatedServices: ['sqs', 'kinesis'],
    box: 1,
    reviewsCount: 0,
  },
  {
    id: 'fc-comp-secrets-vs-ssm',
    deckId: 'comparisons',
    title: 'Comparison: AWS Secrets Manager vs SSM Parameter Store',
    category: 'Security',
    front: 'When should you choose Secrets Manager over Systems Manager Parameter Store?',
    back: '• Secrets Manager: Costs $0.40/secret/mo. Includes NATIVE AUTOMATIC ROTATION for RDS, Redshift, DocumentDB via Lambda.\n• SSM Parameter Store: Standard parameters are FREE. SecureString encrypts with KMS. NO native automatic rotation (requires custom Lambda/EventBridge setup).',
    keyTakeaway: 'If automatic credential rotation without custom code is required, choose Secrets Manager.',
    commonTrap: 'SSM Parameter Store is free, but if the question asks for automatic rotation of database passwords, Secrets Manager is mandatory.',
    relatedServices: ['secrets-manager', 'kms'],
    box: 1,
    reviewsCount: 0,
  },
];

export function getAllFlashcards(): Flashcard[] {
  return FLASHCARDS;
}

export function getFlashcardsByDeck(deckId: 'services' | 'domains' | 'traps' | 'comparisons'): Flashcard[] {
  return FLASHCARDS.filter((c) => c.deckId === deckId);
}

export function getFlashcardById(id: string): Flashcard | undefined {
  return FLASHCARDS.find((c) => c.id === id);
}
